from .certificate_service import CertificateService
from app.services.documentos_office_service import obtener_tipo_documento
from app.services.alumno_service import AlumnoService
from .controlador_service import CertificadoController
